/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheRideRouteImport } from './routes/the-ride'
import { Route as JoinRouteImport } from './routes/join'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CoffeeRouteImport } from './routes/coffee'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RideIndexRouteImport } from './routes/ride/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RideActivateRouteImport } from './routes/ride/activate'

const TheRideRoute = TheRideRouteImport.update({
  id: '/the-ride',
  path: '/the-ride',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CoffeeRoute = CoffeeRouteImport.update({
  id: '/coffee',
  path: '/coffee',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RideIndexRoute = RideIndexRouteImport.update({
  id: '/ride/',
  path: '/ride/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const RideActivateRoute = RideActivateRouteImport.update({
  id: '/ride/activate',
  path: '/ride/activate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coffee': typeof CoffeeRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/the-ride': typeof TheRideRoute
  '/ride/activate': typeof RideActivateRoute
  '/admin/': typeof AdminIndexRoute
  '/ride/': typeof RideIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coffee': typeof CoffeeRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/the-ride': typeof TheRideRoute
  '/ride/activate': typeof RideActivateRoute
  '/admin': typeof AdminIndexRoute
  '/ride': typeof RideIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coffee': typeof CoffeeRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/the-ride': typeof TheRideRoute
  '/ride/activate': typeof RideActivateRoute
  '/admin/': typeof AdminIndexRoute
  '/ride/': typeof RideIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/coffee'
    | '/gallery'
    | '/join'
    | '/the-ride'
    | '/ride/activate'
    | '/admin/'
    | '/ride/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/coffee'
    | '/gallery'
    | '/join'
    | '/the-ride'
    | '/ride/activate'
    | '/admin'
    | '/ride'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/coffee'
    | '/gallery'
    | '/join'
    | '/the-ride'
    | '/ride/activate'
    | '/admin/'
    | '/ride/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CoffeeRoute: typeof CoffeeRoute
  GalleryRoute: typeof GalleryRoute
  JoinRoute: typeof JoinRoute
  TheRideRoute: typeof TheRideRoute
  RideActivateRoute: typeof RideActivateRoute
  AdminIndexRoute: typeof AdminIndexRoute
  RideIndexRoute: typeof RideIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/the-ride': {
      id: '/the-ride'
      path: '/the-ride'
      fullPath: '/the-ride'
      preLoaderRoute: typeof TheRideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coffee': {
      id: '/coffee'
      path: '/coffee'
      fullPath: '/coffee'
      preLoaderRoute: typeof CoffeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ride/': {
      id: '/ride/'
      path: '/ride'
      fullPath: '/ride/'
      preLoaderRoute: typeof RideIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ride/activate': {
      id: '/ride/activate'
      path: '/ride/activate'
      fullPath: '/ride/activate'
      preLoaderRoute: typeof RideActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CoffeeRoute: CoffeeRoute,
  GalleryRoute: GalleryRoute,
  JoinRoute: JoinRoute,
  TheRideRoute: TheRideRoute,
  RideActivateRoute: RideActivateRoute,
  AdminIndexRoute: AdminIndexRoute,
  RideIndexRoute: RideIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
